name: PreTeXt-CLI Actions
on:
    # Runs on pull requests
    pull_request:
        branches: ["*"]
    # Runs on pushes to main
    push:
        branches: ["main"]
    # Runs on demand
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        # container: oscarlevin/pretext:full

        outputs:
            check-cloudflare: ${{ steps.check-cloudflare.outcome }}
            check-ghpages: ${{ steps.check-ghpages.outcome }}

        steps:
            - name: Checkout source
              uses: actions/checkout@v4

            - name: install deps
              run: pip install -r requirements.txt

            - name: build deploy_targets
              run: pretext build
            - name: stage deployment
              run: pretext deploy --stage-only

            - name: Bundle output/stage as artifact
              uses: actions/upload-artifact@v4
              with:
                  name: deploy
                  path: output/stage
            
            - name: Run if Cloudflare is enabled
              id: check-cloudflare
              env: 
                  cloudflare_project_name: ${{ secrets.CLOUDFLARE_PROJECT_NAME }}
              if: env.cloudflare_project_name != ''
              run: echo Cloudflare enabled
            
            - name: Run if Ghpages is enabled
              id: check-ghpages
              env: 
                  ghpages_enabled: ${{ secrets.GHPAGES_ENABLED }}
              if: env.ghpages_enabled == 'yes' && github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
              run: echo Ghpages enabled

    deploy-cloudflare:
        runs-on: ubuntu-latest
        needs: build
        if: needs.build.outputs.check-cloudflare == 'success'

        steps:
            - name: Download artifact
              uses: actions/download-artifact@v4
              with:
                  name: deploy
                  path: deploy
            - name: Create 404.html
              run: echo "404 page not found" >> deploy/404.html
            - name: Publish to Cloudflare
              uses: cloudflare/pages-action@v1
              with:
                  apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
                  accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
                  projectName:${{ secrets.CLOUDFLARE_PROJECT_NAME }}
                  directory: deploy
                  gitHubToken: ${{ secrets.GITHUB_TOKEN }}

    deploy-ghpages:
        runs-on: ubuntu-latest
        needs: build
        if: needs.build.outputs.check-ghpages == 'success'
        permissions:
            contents: read
            pages: write
            id-token: write
        concurrency:
            group: "page"
            cancel-in-progress: false
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        steps:
            - name: Download website artifact
              uses: actions/download-artifact@v4
              with:
                  name: deploy
                  path: deploy
            - name: Setup GitHub Pages
              id: check
              uses: actions/configure-pages@v4
            - name: Upload artifact
              uses: actions/upload-pages-artifact@v3
              with:
                  path: deploy
            - name: Deploy to Github Pages
              id: deployment
              uses: actions/deploy-pages@v4
