name: PreTeXt-CLI Actions
on:
    # Runs on pull requests
    pull_request:
        branches: ["*"]
    # Runs on pushes to main
    push:
        branches: ["main"]
    # Runs on demand
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        # container: oscarlevin/pretext:full

        steps:
            - name: Checkout source
              uses: actions/checkout@v4

            - name: install deps
              run: pip install -r requirements.txt

            - name: build deploy_targets
              run: pretext build
            - name: stage deployment
              run: pretext deploy --stage-only

            - name: Bundle output/stage as artifact
              uses: actions/upload-artifact@v4
              with:
                  name: deploy
                  path: output/stage
            
            - name: Check project.ptx for deploy-cloudflare
              id: check-cloudflare
              run: echo 'project_name=foobar' >> "$GITHUB_OUTPUT" # pretext deploy --cloudflare
            
            - name: Check project.ptx for deploy-ghpages
              id: check-ghpages
              run: echo 'enabled=yes' >> "$GITHUB_OUTPUT" # pretext deploy --enabled

    deploy-cloudflare:
        runs-on: ubuntu-latest
        needs: build
        if: ${{ needs.build.check-cloudflare.outputs.project_name != '' }}

        steps:
            - name: Download artifact
              uses: actions/download-artifact@v4
              with:
                  name: deploy
                  path: deploy
            - name: Create 404.html
              run: echo "404 page not found" >> deploy/404.html
            - name: Publish to Cloudflare
              uses: cloudflare/pages-action@v1
              with:
                  apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
                  accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
                  projectName: ${{ needs.build.check-cloudflare.outputs.project_name }}
                  directory: deploy
                  gitHubToken: ${{ secrets.GITHUB_TOKEN }}

    deploy-ghpages:
        runs-on: ubuntu-latest
        needs: build
        if: ${{ needs.build.check-ghpages.outputs.enabled == 'yes' }}
        permissions:
            contents: read
            pages: write
            id-token: write
        concurrency:
            group: "page"
            cancel-in-progress: false
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        steps:
            - name: Download website artifact
              uses: actions/download-artifact@v4
              with:
                  name: deploy
                  path: deploy
            - name: Setup GitHub Pages
              id: check
              uses: actions/configure-pages@v4
            - name: Upload artifact
              uses: actions/upload-pages-artifact@v3
              with:
                  path: deploy
            - name: Deploy to Github Pages
              id: deployment
              uses: actions/deploy-pages@v4
